language: ruby

script:
  - ruby tests/examples_test.rb

after_script:
  - curl -o trigger.sh https://raw.githubusercontent.com/Arthaey/travis-build-history-badges/master/bin/trigger_badges_update.sh
  - sh trigger.sh
